function(find_taglib)
  find_package(taglib)
  if(${taglib_FOUND})
    message("Using taglib from Conan")
  else()
    message("Couldn't find taglib with find_package. Attempting pkg-config")
    find_package(PkgConfig)
    pkg_check_modules(taglib REQUIRED taglib)
    message("Falling back to using system taglib")
    add_library(taglib::taglib INTERFACE IMPORTED)
    target_link_libraries(taglib::taglib INTERFACE ${taglib_LIBRARIES})
    target_include_directories(taglib::taglib INTERFACE ${taglib_INCLUDE_DIRS})
  endif()
endfunction()
